server:
  address: "127.0.0.1"
  port: 9998

api:
  gptgod_url: "https://api.gptgod.online/v1/chat/completions"

model_mapping:
  ggl-4: "gpt-4-turbo"
  gclaude-3-5-sonnet: "claude-3-5-sonnet-20240620"
  gclaude-3-5-sonnet-20241022: "claude-3-5-sonnet-20241022"
  gpt-4o: "gpt-4o"
